[package]
name = "deadlock-gameinfo-editor"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
steamlocate = "2.1.0"
anyhow = "1.0.104"
crossterm = "0.29.0"
inquire = "0.9.4"

[build-dependencies]
winresource = "0.1.31"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true
lto = true
